### ISSUE TITLE
Comparison of `undefined` against `null`

### ISSUE THREAD

**Issue by LukasPietzschmann** [Tanikai/uniulm_mensa_frontend#2]
So I noticed that you pass `undefined` to a `MealElement` [here](https://github.com/Tanikai/uniulm_mensa_frontend/blob/dee6b17aa336319715f39dc5b4b96180e96fce9e/src/layouts/canteen-meals/CanteenMeals.tsx#L38) to indicate that there is no meal to display. But in [MealElement.tsx:11](https://github.com/Tanikai/uniulm_mensa_frontend/blob/dee6b17aa336319715f39dc5b4b96180e96fce9e/src/layouts/canteen-meals/meal-element/MealElement.tsx#L11) you are comparing this value against `null` not `undefined`.

IMHO there are two ways to go about this issue:
1. Fix the comparison directly
2. Move this logic out of the `MealElement` into `CanteenMeals`

I'd prefer option 2. as this is not really a concern of an individual meal, and a similar check already exists in `CanteenMeals`.

**Comment by Tanikai** [comment]
The mentioned line uses `==` instead of `===`. This means that if the meal is undefined, it still returns the "canteen closed" component, as `null == undefined` returns `true`.

However, as you've said in your last sentence, it's not really the concern of the `MealElement`. I'll move it to `CanteenMeals`.
